FROM ubuntu:24.04
LABEL org.opencontainers.image.authors="Nicholas Myers, Eric Mikida"

RUN apt update
RUN apt install -y make

# Utility setup
RUN apt install -y unzip

# OCaml setup
RUN apt-get install -y ocaml=4.14.1-1ubuntu1

# Python setup
RUN apt install -y python3

# Install autodriver
WORKDIR /home
RUN useradd autolab
RUN useradd autograde
RUN mkdir autolab autograde output
RUN chown autolab:autolab autolab
RUN chown autolab:autolab output
RUN chown autograde:autograde autograde
RUN apt update && apt install -y sudo
RUN apt install -y git
RUN git clone https://github.com/autolab/Tango.git
WORKDIR Tango/autodriver
RUN make clean && make
RUN cp autodriver /usr/bin/autodriver
RUN chmod +s /usr/bin/autodriver

# Clean up
WORKDIR /home
RUN apt -y autoremove
RUN rm -rf Tango/

# Check installation
RUN ls -l /home
RUN which autodriver
RUN ocaml --version
RUN python3 --version
