FROM ubuntu:24.04
LABEL org.opencontainers.image.authors="Vincent Chan <vichan39@buffalo.edu>"

ARG OCAML_VERSION=4.14.2
ARG USER_NAME=autograde

# Utility setup
RUN apt-get update
RUN apt-get install -y apt-utils build-essential
RUN apt-get install -y ca-certificates curl git python3
RUN apt-get install -y opam bubblewrap rsync unzip

# Install autodriver
WORKDIR /home
RUN useradd autolab
RUN useradd autograde
RUN mkdir autolab autograde output
RUN chown autolab:autolab autolab
RUN chown autolab:autolab output
RUN chown autograde:autograde autograde
RUN apt update && apt install -y sudo
RUN apt install -y git
RUN git clone https://github.com/autolab/Tango.git
WORKDIR Tango/autodriver
RUN make clean && make
RUN cp autodriver /usr/bin/autodriver
RUN chmod +s /usr/bin/autodriver

# OPAM Setup
WORKDIR /home/${USER_NAME}
USER ${USER_NAME}
ENV PATH=/home/${USER_NAME}/.opam/${USER_NAME}_${OCAML_VERSION}/bin:$PATH
RUN opam init --bare -ay
RUN opam switch create ${USER_NAME}_${OCAML_VERSION} ocaml-base-compiler.${OCAML_VERSION}
RUN opam install -y merlin ocaml-lsp-server ocamlformat utop
RUN chmod +x .opam/opam-init/*.sh
RUN echo 'eval $(opam env)' >> .bashrc
USER root
RUN echo "export PATH=/home/${USER_NAME}/.opam/${USER_NAME}_${OCAML_VERSION}/bin:$PATH" >> /etc/environment

# Clean up
RUN apt-get -y autoremove
RUN rm -rf Tango/
WORKDIR /home

# Check installation
RUN ls -l /home
USER ${USER_NAME}
RUN which autodriver
RUN which ocaml
RUN ocamlc --version
RUN python3 --version
USER root
